services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestunifserv_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RISK_CSV_PATH=${RISK_CSV_PATH}
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: gestunifserv_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
